# Fly.io 配置文件
app = "lbmx-spread-monitor"
primary_region = "nrt"  # 東京區域，可改為 hkg (香港) 或 sin (新加坡)

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machines]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
